# Generated by Django 5.2.4 on 2025-07-17 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ip_tracking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reason", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Blocked IP",
                "verbose_name_plural": "Blocked IPs",
                "ordering": ["-created_at"],
            },
        ),
    ]
